### PR TITLE
Add ELb deregister/register

### PR DESCRIPTION
**Pull request by igordavid**
Initial Pull request with an idea how we can achieve detaching and attaching EC2 instances from ELBs. Needs to be tested

### CODE REVIEW

**Comment by tangerinedream** [comment]
Hi Igor,
Thanks for Pull request.  This is a very interesting enhancement.

A few things:
1) Would it be possible to separate the functionality into a method as opposed to inline?  Perhaps a method called "addressELBRegistration()" ?

2) As this method will be called for every instance being Started, will there be a RateLimitExceeded impact in making these repeated calls to 
`elf.all_elbs = self.elb.describe_load_balancers()` ?

3) Perhaps a cut/paste issue but the code here:
`self.elb = boto3.client('elb', region_name='eu-west-1', region_name=self.dynamoDBRegion)`
should probably the python instance variables values:
`self.elb = boto3.client('elb', region_name=self.workloadRegion, region_name=self.ddbRegion)`


Thanks,
Gary

**Comment by tangerinedream** [comment]
Hi Igor,
I like the changes you made.  I have two things:

1.  Minor point.  Both of the exception messages in Orchestrator.py should be changed to reflect the exception is coming from establishing the elb client, not the dynamoDB client.

2.  Regarding the deregistration, and then registration, I have a question.  My understanding is that the issue is upon Starting the instance, it may no longer be registered with the ELB, and thus someone needs to manually register the instance with the ELB.  If that is true, why would we ever need to actually deregister the instance first before calling register?  This also makes another API call to AWS to we want to avoid.  Perhaps there is a valid reason required that we must call deregister but if so, could you please explain?

I like the optimization you added, by gathering the ELB info in the Orchestrator.

**Comment by igordavid** [comment]
Hi Gary,

Please find answers below:

1. This has been fixed now

2. The problem happens when EC2 instance which is registered with ELB is stopped, without being de-registered from ELB. When that instance is started, ELB won't route traffic to it and will consider it un-healthy, required action is to de-register instance and register it again with that ELB. This is not happening every time but occasionally, causing application not working properly.

From AWS docs:

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Stop_Start.html#instance_stop

"
If you've registered the instance with a load balancer, it's likely that the load balancer won't be able to route traffic to your instance after you've stopped and restarted it. You must de-register the instance from the load balancer after stopping the instance, and then re-register after starting the instance. For more information, see Register or Deregister EC2 Instances for Your Classic Load Balancer in the Classic Load Balancer Guide. "

**Comment by tangerinedream** [comment]
Hi Igor,

Recommend adding a Filter to the ELB search, to isolate only ELB's with the Workload, for processing.

This should be fairly straight forward, using the Tag on the ELBs corresponding to "WorkloadFilterTagValue" in the Workload Table.  That value indicates the name of the specific workload.

Documented on the main page (https://github.com/tangerinedream/AWS_EC2_Scheduler/)

Thanks for your input as well !

**Comment by igordavid** [comment]
Hi Gary,

Unfortunately there is no Filter option when running DescribeLoadBalancers API. We can either specify certain ELB, or if we don't specify anything it will return a list of all ELBs.

http://boto3.readthedocs.io/en/latest/reference/services/elb.html#ElasticLoadBalancing.Client.describe_load_balancers

https://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/API_DescribeLoadBalancers.html

However I don't see this as a major drawback if we describe all ELBs, as AWS is not charging for API describe calls I believe, it's just obtaining bigger list (or maybe I am missing some other reason why this is bad?)

**Review by tangerinedream — CHANGES_REQUESTED** [review]
Igor, would you kindly change the log level of the following lines in Worker ?

From Info to Debug: lines #73, #76, #82
From Info to Warning: lines: #78, #84

Thanks

**Comment by igordavid** [comment]
Hi @tangerinedream ,

Log level changes has been made

**Review by tangerinedream — APPROVED** [review]

**Comment by tangerinedream** [comment]
Igor,
Thank you for your contribution.  Instances Stopped which are currently registered with ELB will now be deregistered and reregistered at Start time.  This addresses an intermittent issue whereby the Started instance does not always come up as being registered with the ELB.
Thanks again,
Gary

**Pull request merged**
